### ISSUE TITLE
Update Google Auth chapter to reflect git-crypt as the primary local encryption method

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eha-ma-handbook#39]
As we're moving to gh-actions over RSConnect, we can work with this assumption.

Need some big flashing letters to encrypt the `.env` file.

**Comment by collinschwantes** [comment]
Much of the git-crypt content in this chapter should probably be moved to the encryption chapter and the encryption chapter should precede the google-auth chapter.
