### ISSUE TITLE
Replace DC resources with other learning alternatives

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eha-ma-handbook#61]
As we don't use DC anymore, we still need to clear out that portion of the handbook (as well as just deleting the formal training program approach we used when we paid for subscription). 

Prompted by a request from @wbagge, who wanted a replacement for "Foundations of Probability in R".  Initial findings, which I don't yet know the quality of. Please comment on what you find in these and anything else useful! 

  - Probability, Statistics, and Data: A fresh approach using R: https://mathstat.slu.edu/~speegle/_book/ (found searching ["The Big Book of R"](https://www.bigbookofr.com), an index of online R books! 
  - An Introduction to Probability and Simulation: https://bookdown.org/kevin_davisross/probsim-book/

**Comment by noamross** [comment]
A short primer, maybe taken from the DC course?: https://rpubs.com/trombleydc/extra_credit_11_6_2017

**Comment by noamross** [comment]
There's also dataquest.io, which I have received good reviews about (at least a few years ago), and has DC-style courses including a probability series . $49 / mo or $400/year for an individual, $283/seat/year for teams: https://www.dataquest.io/path/data-analyst-r/

**Comment by collinschwantes** [comment]
Files that reference data camp

- [ ] ./getting-help.Rmd
- [ ] ./training-resources-and-plans.Rmd
- [ ] ./versioning.Rmd
- [ ] ./r.Rmd
