### ISSUE TITLE
Clarify DMP process, especially with partners

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eha-ma-handbook#76]
Related to #73, but a bit more expansive - the DMP process as outlines is a bit mechanical and should emphasize the data sharing policies and outcomes and the need to evaluate and negotiate them.  In particular, there should be explicit steps in DMP preparation that PIs and project partners should communicate, clarify data sharing in the proposal prep stage and everyone should sign off the DMP and be aware of the requirements that it meets.  We want to avoid situations where project partners (including, potentially the PI), are unaware of what they are committed to under agency policy or their own DMPs.  This should be part of the review checklist.

**Comment by collinschwantes** [comment]
- [ ] emphasize data sharing policies and outcomes
- [ ] emphasize the need to evaluate and negotiate the data sharing policies and outcomes with partners
- [ ] explicitly state that PIs and project partners should come to an agreement about the data sharing components at the proposal stage
