### ISSUE TITLE
Update dependency management 

### ISSUE THREAD

**Issue by collinschwantes** [ecohealthalliance/eha-ma-handbook#97]
- [x] Drop references to packrat
- [x] Add references to renv
- [x] Add dtra ml FORTRAN materials
- [x] Check that all links work

**Comment by mekaczmarek** [comment]
CXX14FLAGS += -O3 -arch arm64 -ftemplate-depth-256
FC = /opt/homebrew/Cellar/gcc/13.2.0/bin/gfortran
F77 = /opt/homebrew/Cellar/gcc/13.2.0/bin/gfortran
FLIBS = -L/opt/homebrew/Cellar/gcc/13.2.0/lib/gcc/13
